spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(seED3AiFe25p3mcVAh0ig70xnYOvNXhCQVQfG6hzPJMakUVOmpyAbVuLtficpXmM)
    username: ENC(ehcwT7PYoobhiKRiD4yTBg==)
    password: ENC(7pWHebA5OeCD47PHZT2rv9SWUinpPQl7)

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
